name: ci

on:
  push:
    branches:
      - main
      - "feat/**"
      - "fix/**"
      - "chore/**"
      - "docs/**"
      - "test/**"
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Go test
        run: go test ./...

      - name: Go vet
        run: go vet ./...

      - name: Go build
        run: go build ./cmd/slap-mac-replica
